# Generated by Django 2.1.2 on 2019-08-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=20)),
                ('sname', models.CharField(max_length=100)),
                ('scontact', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
